modLoader = "javafml"
loaderVersion = "[${forgeshortversion},)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Library/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftblibrary"
version = "${version}"
displayName = "FTB Library"
authors = "LatvianModder"
description = '''
FTB Library adds nothing.
'''

[[dependencies.ftblibrary]]
modId = "forge"
mandatory = true
versionRange = "[${forgeversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "architectury"
mandatory = true
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"
