name: Java CI - Build on Push

on:
  push:
    branches: [ main, "1.*" ]
  workflow_dispatch:
    inputs:
      skip_maven_publish:
        description: 'Skip Maven publishing'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 30 # Gets the last 30 commits so the changelog might work
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon
      - name: Publish to Maven
        uses: gradle/gradle-build-action@v2
        if: github.event.inputs.skip_maven_publish != 'true'
        env:
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
          SNAPSHOT: true
        with:
          arguments: publish --no-daemon